version: '3.9'
name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    volumes:
      - type: bind
        source: ./server/config.ini
        target: /config.ini

  # Add yaml anchor to avoid duplicating code and reducing the file size
  client1: &client_config
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - type: bind
        source: ./client/config.yaml
        target: /config.yaml

  client2:
    <<: *client_config
    container_name: client2
    environment:
      - CLI_ID=2

  client3:
    <<: *client_config
    container_name: client3
    environment:
      - CLI_ID=3

  client4:
    <<: *client_config
    container_name: client4
    environment:
      - CLI_ID=4

  client5:
    <<: *client_config
    container_name: client5
    environment:
      - CLI_ID=5

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
