version: '3.9'
name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    volumes:
      - type: bind
        source: ./server/config.ini
        target: /config.ini

  # Add yaml anchor to avoid duplicating code and reducing the file size
  client1: &client_config
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - type: bind
        source: ./client/config.yaml
        target: /config.yaml

  # we can now reference the `client_config` anchor from another service to copy most of the config without increasing the file size
  # <<: *client_config references the client configuration from the anchor created above
  client2:
    <<: *client_config
    container_name: client2
    environment:
      - CLI_ID=2

  client3:
    <<: *client_config
    container_name: client3
    environment:
      - CLI_ID=3

  client4:
    <<: *client_config
    container_name: client4
    environment:
      - CLI_ID=4

  client5:
    <<: *client_config
    container_name: client5
    environment:
      - CLI_ID=5

  client6:
    <<: *client_config
    container_name: client6
    environment:
      - CLI_ID=6

  client7:
    <<: *client_config
    container_name: client7
    environment:
      - CLI_ID=7

  client8:
    <<: *client_config
    container_name: client8
    environment:
      - CLI_ID=8

  client9:
    <<: *client_config
    container_name: client9
    environment:
      - CLI_ID=9

  client10:
    <<: *client_config
    container_name: client10
    environment:
      - CLI_ID=10

  client11:
    <<: *client_config
    container_name: client11
    environment:
      - CLI_ID=11

  client12:
    <<: *client_config
    container_name: client12
    environment:
      - CLI_ID=12

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
