version: '3.9'
name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net

  # Add yaml anchor to avoid duplicating code and reducing the file size
  client1: &client_config
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - server

  # we can now reference the `client_config` anchor from another service to copy most of the config without increasing the file size
  # <<: *client_config references the client configuration from the anchor created above
  client2:
    <<: *client_config
    container_name: client2
    environment:
      - CLI_ID=2

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
